-- One shared filter bar for all five personas: every persona query honours the
-- same four params, which is what lets a tab switch hold scope.
SELECT 'MARKET' AS DIM, MARKET AS VAL FROM STARTER_KIT.SUPERSTORE GROUP BY 2
UNION ALL
SELECT 'CATEGORY', CATEGORY FROM STARTER_KIT.SUPERSTORE GROUP BY 2
UNION ALL
SELECT 'SEGMENT', SEGMENT FROM STARTER_KIT.SUPERSTORE GROUP BY 2
UNION ALL
SELECT 'YEAR', ORDER_YEAR FROM STARTER_KIT.SUPERSTORE GROUP BY 2
ORDER BY 1, 2
